backend:
  name: github
  branch: master
  repo: jenskrumsieck/porphystruct_website

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'relation_files'
    label: 'Relations'
    files:
      - name: "categories"
        label: "Categories"        
        file: "content/categories.json"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Categories
            name: categories
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
  - name: 'manuals'
    label: 'Manuals'
    label_singular: 'Manual'
    folder: 'content/manual'
    create: true
    slug: '{{slug}}'
    preview_path: 'manual/{{slug}}'
    sortable_fields: ['priority', 'category']
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'relation_files',
          file: "categories",
          search_fields: ["categories.*.name"],
          display_fields: ["categories.*.name"],
          value_field: "categories.*.name"
        }
      - { label: 'Priority', name: 'priority', widget: 'number' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
